Resources:
  AppSyncElasticSearchServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: appsync-elasticsearch-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
               - 'sts:AssumeRole'
      Description: 'IAM Role of AppSync using ElasticSearch'
      # IAMポリシーの定義
      Policies:
        - PolicyName: elasticsearch_policy_${opt:stage, self:custom.defaultStage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'es:ESHttpGet'
                Resource:
                  - '*'
      Tags:
        - Key: Project
          Value: ${file(../serverless-common.yml):appname}
        - Key: Environment
          Value: ${opt:stage, self:custom.defaultStage}

Outputs:
  AppSyncElasticSearchServiceRoleArn:
    Value: !GetAtt AppSyncElasticSearchServiceRole.Arn

