Resources:
  AppSyncLambdaServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: appsync-lambda-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
               - 'sts:AssumeRole'
      Description: 'IAM Role of AppSync using Lambda'
      # IAMポリシーの定義
      Policies:
        - PolicyName: lambda_policy_${opt:stage, self:custom.defaultStage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'lambda:invokeFunction'
                Resource:
                  - '*'
      Tags:
        - Key: Project
          Value: ${file(../serverless-common.yml):appname}
        - Key: Environment
          Value: ${opt:stage, self:custom.defaultStage}

Outputs:
  AppSyncLambdaServiceRoleArn:
    Value: !GetAtt AppSyncLambdaServiceRole.Arn

