Resources:
  AppSyncLoggingServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: appsync-logging-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'appsync.amazonaws.com'
            Action:
               - 'sts:AssumeRole'
      Description: 'IAM Role of AppSync using Cloudwatch Logs'
      # IAMポリシーの定義
      Policies:
        - PolicyName: cloudwatch_logs_policy_${opt:stage, self:custom.defaultStage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:DescribeLogGroups'
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                  - 'logs:GetLogEvents'
                  - 'logs:FilterLogEvents'
                Resource:
                  - '*'
      Tags:
        - Key: Project
          Value: ${file(../serverless-common.yml):appname}
        - Key: Environment
          Value: ${opt:stage, self:custom.defaultStage}

Outputs:
  AppSyncLoggingServiceRoleArn:
    Value: !GetAtt AppSyncLoggingServiceRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-AppSyncLoggingServiceRoleArn"

